
name: Release

on:
  - push

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y qt5-default qtbase5-dev qttools5-dev libqt5svg5-dev libpq-dev libxml2-dev

      - name: Checkout Release Scripts
        uses: actions/checkout@v2

      - name: Checkout pgModeler
        run: |
          git clone --single-branch --branch master https://github.com/pgmodeler/pgmodeler.git

      - name: Checkout pgModeler Plugins
        run: |
          git clone --single-branch --branch master https://github.com/pgmodeler/plugins.git

      - name: Move Plugins to pgModeler Directory
        run: |
          mv plugins pgmodeler
      
      - name: Archive Source
        run: |
          tar -czvf pgmodeler-source.tar.gz pgmodeler

      - name: Upload Source Archive
        uses: actions/upload-artifact@v2
        if: ${{ !env.ACT }}
        with:
          name: pgmodeler-source.tar.gz
          path: pgmodeler-source.tar.gz

      - name: Build
        run: |
          export INSTALLATION_ROOT=$(pwd)/AppDir
          cd pgmodeler
          qmake -r CONFIG+=release PREFIX=$INSTALLATION_ROOT BINDIR=$INSTALLATION_ROOT \
            PRIVATEBINDIR=$INSTALLATION_ROOT PRIVATELIBDIR=$INSTALLATION_ROOT/lib pgmodeler.pro
          make -j$(nproc)
          make install

      - name: Archive Binaries
        run: |
          tar -czvf pg-modeler-x86_64.tar.gz AppDir

      - name: Upload Binary Archive
        uses: actions/upload-artifact@v2
        if: ${{ !env.ACT }}
        with:
          name: pgmodeler-x86_64.tar.gz
          path: pgmodeler-x86_64.tar.gz
